@startuml UC-MGDISASTER-011 - Menambahkan data bencana alam secara bulk
skinparam wrapWidth 140

title Menambahkan data bencana alam secara bulk

|Administrator & Perwakilan BPBD|
start
:Memilih menu tambah bulk data bencana alam;

|Sistem|
:Menampilkan menu tambah bulk data bencana alam;

|Administrator & Perwakilan BPBD|
:Mengunduh template isian;

|Storage Bucket|
:Mengambil url template file;

|Sistem|
:Mengirimkan template file sebagai unduhan;

|Administrator & Perwakilan BPBD|
:Mengunggah file excel data bulk bencana alam;
:Mengklik tombol unggah;

|Sistem|
:Menampilkan popup konfirmasi;

|Administrator & Perwakilan BPBD|
:Mengonfirmasi pengisian data bulk bencana alam;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |Sistem|
  :Mencari kesalahan pengisian data pada data bulk;

  if () then (Ada kesalahan pengisian)
    |Sistem|
    :Menampilkan pesan error;
  else (Tidak ada kesalahan pengisian)
    |DBMS|
    :Menyimpan data bencana alam;

    |Storage Bucket|
    if () then (Tidak ada unggahan)
    else (Ada unggahan)
      :Menyimpan media unggahan;
    endif

    |Sistem|
    fork
      :Menampilkan pesan berhasil;
    fork again
      :Menampilkan menu daftar data bencana alam;
    endfork
  endif
endif

|Administrator & Perwakilan BPBD|
stop

@enduml