@startuml UC-MGDISASTER-001 - Melihat daftar laporan bencana alam dari pengguna
skinparam wrapWidth 140

title Melihat daftar laporan bencana alam dari pengguna

|Administrator & Perwakilan BPBD|
start
:Memilih menu daftar laporan bencana alam dari pengguna;
:Memilih filter dan sort;

|Sistem|
:Menampilkan menu daftar laporan bencana alam dari pengguna;

stop

@enduml