@startuml UC-MGDISASTER-004 - Menutup laporan bencana alam yang tidak valid
skinparam wrapWidth 140

title Menutup laporan bencana alam yang tidak valid

|Administrator & Perwakilan BPBD|
start
:Memilih menu detail laporan bencana alam;

|DBMS|
:Mengambil data laporan bencana alam;

|Sistem|
:Menampilkan menu detail laporan bencana alam;

|Administrator & Perwakilan BPBD|
:Memilih opsi 'Laporan tidak valid';
:Mengisi alasan;
:Memilih tombol simpan;

|Sistem|
:Menampilkan popup konfirmasi;

|Administrator & Perwakilan BPBD|
:Mengonfirmasi penutupan laporan;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |Sistem|
  :Memvalidasi data alasan penutupan laporan;

  if () then (Data tidak valid)
    :Menampilkan pesan error validasi;
  else (Data valid)
    |DBMS|
    :Menyimpan penutupan laporan;

    |Sistem|
    fork
      :Menampilkan pesan berhasil;
    fork again
      :Menampilkan menu daftar laporan bencana alam dari pengguna;
    endfork
  endif
endif

|Administrator & Perwakilan BPBD|
stop

@enduml