@startuml UC-MGDISASTER-010 - Menghapus data bencana alam
title Menghapus data bencana alam

|Administrator & Perwakilan BPBD|
start
:Memilih menu daftar data bencana alam;
:Memilih filter dan sort;

|Sistem|
:Menampilkan menu daftar data bencana alam;

|Administrator & Perwakilan BPBD|
:Memilih menu detail data bencana alam;

|Sistem|
:Menampilkan menu detail data bencana alam;

|Administrator & Perwakilan BPBD|
:Mengklik tombol hapus;

|Sistem|
:Menampilkan popup konfirmasi;

|Administrator & Perwakilan BPBD|
:Mengonfirmasi penghapusan data bencana alam;

if (Konfirmasi popup) then (Batal)
else (Ok)
  |DBMS|
  :Menghapus data bencana alam;

  if (Ada media unggahan?) then (Tidak ada)
  else (Ada)
    |Storage Bucket|
    :Menghapus media unggahan;
  endif

  |Sistem|
  :Menampilkan pesan berhasil;
  :Menampilkan menu daftar data bencana alam;
endif

|Administrator & Perwakilan BPBD|
stop

@enduml