@startuml UC-MGDISASTER-005 - Melihat daftar data bencana alam
skinparam wrapWidth 140

title Melihat daftar data bencana alam

|Administrator & Perwakilan BPBD|
start
:Memilih menu data bencana alam;
:Memilih filter dan sort;

|Sistem|
:Menampilkan menu data laporan bencana alam;

stop

@enduml