@startuml UC-MGDISASTER-008 - Mengubah data bencana alam
skinparam wrapWidth 140

title Mengubah data bencana alam

|Administrator & Perwakilan BPBD|
start
:Memilih menu daftar data bencana alam;
:Memilih filter dan sort;

|Sistem|
:Menampilkan menu daftar data bencana alam;

|Administrator & Perwakilan BPBD|
:Memilih menu edit data bencana alam;

|Sistem|
:Menampilkan menu edit data bencana alam;

|Administrator & Perwakilan BPBD|
:Mengisi data bencana alam;
:Mengunggah media (foto atau video) jika ada;
:Mengklik tombol simpan;

|Sistem|
:Menampilkan popup konfirmasi;

|Administrator & Perwakilan BPBD|
:Mengonfirmasi perubahan data bencana alam;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |DBMS|
  :Menyimpan perubahan data bencana alam;

  if () then (Tidak ada unggahan)
  else (Ada unggahan)
    |Storage Bucket|
    :Menyimpan media unggahan;
  endif

  |Sistem|
  fork
    :Menampilkan pesan berhasil;
  fork again
    :Menampilkan menu detail data bencana alam yang telah diubah;
  endfork
endif

|Administrator & Perwakilan BPBD|
stop

@enduml