@startuml UC-MGDISASTER-002 - Melihat detail laporan bencana alam dari pengguna
skinparam wrapWidth 140

title Melihat detail laporan bencana alam dari pengguna

|Administrator & Perwakilan BPBD|
start
:Memilih menu daftar laporan bencana alam dari pengguna;
:Memilih filter dan sort;

|DBMS|
:Mengambil data laporan-laporan bencana alam pengguna;

|Sistem|
:Menampilkan menu daftar laporan bencana alam dari pengguna;

|Administrator & Perwakilan BPBD|
:Mengklik tombol detail pada laporan yang dipilih;

|DBMS|
:Mengambil data laporan bencana alam;

|Sistem|
:Menampilkan menu detail laporan bencana alam;

stop

@enduml