@startuml UC-MGDISASTER-013 - Melihat log aktivitas data bencana alam;
skinparam wrapWidth 140

title Melihat log aktivitas data bencana alam;

|Administrator & Perwakilan BPBD|
start
:Memilih menu log aktivitas data bencana alam;
:Memilih filter dan sort;

|Sistem|
:Menampilkan menu log aktivitas data bencana alam;

stop

@enduml