@startuml SD-MGACCOUNT-003 - Mengubah password

title Mengubah password

actor ":User" as user
participant ":ProfileUI" as view
participant ":ProfileController" as controller
participant ":ProfileUpdateFormValidator" as validator 
participant ":AuthService" as authService
participant ":UserService" as userService
database ":DBMS" as db

user -> view ++: Membuka menu profile
view -> view: showProfileMenu()

view -> controller ++: getProfile()
  controller -> userService ++: getUserById(userId)
    userService -> db ++: Query user by id
      return userModel
    return userModel
  return userDTO

view -> view: loadUserProfile(userDTO)

== Ubah password ==
user -> view: Memilih tombol ubah password
view -> view: showPasswordChangePopup()

user -> view: Mengisi password lama dan password baru
view -> controller ++: updatePassword(passwordUpdateDTO)
  controller -> validator ++: validate(passwordUpdateDTO)
    return isValid, errorMessages

  alt password data invalid
    controller --> view: isValid, errorMessages
    view -> view: showErrorMessages()
  else password data valid
    controller -> authService ++: updatePassword(passwordUpdateDTO)
      authService -> authService ++: hashPassword(oldPassword)
        return newPasswordHash

      authService -> authService ++: hashPassword(newPassword)
        return newPasswordHash
      
      authService -> db ++: Query check old password hash equality
        return isOldPasswordCorrect
      
      alt old password is incorrect
        authService --> controller: isSuccess, invalidPasswordErrorMessage
        controller --> view: isSuccess, errorMessages 
        view -> view: showErrorMessages()
      else old password is correct
        authService -> userService ++: updateUserPasswordByUserId(userId, newPasswordHash)
          userService -> db ++: Update user password hash by user id
            return transactionStatus
          return isSuccess
        
        return isSuccess
        return isSuccess

        view -> view: showSuccessMessage()
      end
  end