@startuml
title Pemetaan Titik Rawan Gratifikasi 

|UPG|
start

|UPG|
:Memilih menu "Pemetaan 
Titik Rawan Gratifikasi";

|API|
:Memuat peta dinamis;

|Sistem|
:Melakukan request
titik koordinat 
ke database;
|Database|
:Merespons request
titik koordinat;

|Sistem|
:Menampilkan titik 
rawan sebelumnya;

|UPG|
:Menambahkan titik 
rawan baru pada 
peta (klik lokasi);
:Memasukkan data 
titik rawan 
(lokasi, kategori risiko, deskripsi);

|Sistem|
:Validasi data input;
if () then ([Data Tidak Valid])
   :Menampilkan pesan error;
else ([Data Valid])
  |Database|
  :Menyimpan titik rawan 
  baru;
  |API|
  :Memuat peta;
  |Sistem|
  :Menampilkan titik 
  baru;
  :Menampilkan informasi
   terkait titik rawan 
   gratifikasi;
endif

|UPG|
:Melihat ringkasan
 titik rawan pada 
 peta berdasarkan 
 kategori;

stop
@enduml