@startuml UC-AUTH-004 - Memulihkan akun lupa password
skinparam wrapWidth 140

title Memulihkan akun lupa password

|Pengguna|
start

:Memilih menu login;

|Sistem|
:Menampilkan menu login;

|Pengguna|
:Memilih tombol "Lupa password";

|Sistem|
:Menampilkan menu lupa password;

|Pengguna|
:Mengisi alamat email akun;

|DBMS|
:Mencari apakah alamat email sudah terdaftar;

|Sistem|
if () then (Email terdaftar)
  |Email Service|
  :Mengirim kode OTP ke alamat email akun;

  |Sistem|
  :Menampilkan pesan Kode OTP telah dikirimkan;
  :Menampilkan menu kode OTP;

  |Pengguna|
  :Mengisi kode OTP;
  
  |Sistem|
  :Mengecek kode OTP;

  if () then (OTP tidak sesuai)
  else (OTP sesuai)
    :Menampilkan menu ubah password;

    |Pengguna|
    :Mengisi password baru;

    |Sistem|
    :Meng-hash password baru; 

    |DBMS|
    :Menyimpan (hash) password baru;

    |Sistem|
    :Menampilkan pesan berhasil;
    :Menampilkan menu login;
  endif
else (Email tidak terdaftar)
  :Menampilkan pesan email tidak terdaftar;
endif

stop
@enduml