@startuml UC-AUTH-002 - Login
skinparam wrapWidth 140

title Login

|Pengguna|
start
:Memilih menu login;

|Sistem|
:Menampilkan menu login;

|Pengguna|
:Memilih metode login;

if () then (Email)
  :Mengisi data akun;
  :Mengklik tombol login;

  |Sistem|
  :Mengecek kredensial akun;
else (OAuth)
  |OAuth Provider|
  :Menerima data pengguna dari provider OAuth;
endif

|Sistem|
switch ()
case (Kredensial benar)
  :Menyimpan session pengguna;

  fork
    :Menampilkan pesan berhasil;
  fork again
    :Menampilkan halaman peta bencana;
  endfork
case (Kredensial salah)
  :Tampilkan pesan login gagal;
case (Belum terdaftar)
  :Tampilkan pesan akun tidak terdaftar;
endswitch

stop
@enduml