@startuml UC-AUTH-001 - Registrasi
skinparam wrapWidth 140

title Registrasi

|Pengguna|
start
:Memilih menu registrasi;

|Sistem|
:Menampilkan menu registrasi;

|Pengguna|
:Memilih metode registrasi;

if () then (Email)
else (OAuth)
  |Sistem|
  :Menampilkan laman OAuth;
endif

|Pengguna|
:Mengisi data registrasi;

if () then (Registrasi dengan email)
else (Registrasi dengan OAuth)
  |OAuth Provider|
  :Menjalankan callback URL OAuth dari sistem;

  |Sistem|
  :Menerima data pengguna dari provider OAuth;
endif 

|DBMS|
:Mencari apakah email sudah terdaftar atau belum;

|Sistem|
if () then (Email terdaftar)
  |Sistem|
  :Tampilkan pesan email sudah terdaftar;
else (Email tidak terdaftar)
  |DBMS|
  :Menyimpan data registrasi;

  |Sistem|
  :Menyimpan session pengguna;

  fork
    :Menampilkan pesan berhasil;
  fork again
    :Menampilkan halaman peta bencana;
  end fork
endif

|Pengguna|
stop
@enduml