@startuml UC-AUTH-001 - Registrasi
!pragma useVerticalIf on

title Registrasi

|Pengguna|
start
:Memilih menu registrasi;

|Sistem|
:Menampilkan menu registrasi;

|Pengguna|
:Memilih metode registrasi;

if () then (Email)
  :Mengisi data registrasi;

  |DBMS|
  :Mencari apakah sudah terdaftar atau belum;

  |Sistem|
  if () then (Email tidak terdaftar)
    :Tampilkan warna accent success pada input email;

    |Pengguna|
    :Mengklik tombol daftar;

    |Sistem|
    :Menampilkan popup konfirmasi;

    |Pengguna|
    if () then (Konfirmasi ok)
      |DBMS|
      :Menyimpan data registrasi;

      |Sistem|
      :Menampilkan pesan berhasil;
      :Menampilkan halaman peta bencana;
    else (Konfirmasi batal)
    endif
  else (Email terdaftar)
    :Tampilkan pesan email sudah terdaftar;
  endif
else (OAuth)
  |OAuth Provider|
  :Menerima data pengguna dari provider OAuth;
endif 

|Pengguna|
stop
@enduml