@startuml UC-AUTH-003 - Logout
skinparam wrapWidth 140

title Logout

|Pengguna|
start
:Mengklik tombol logout;

|Sistem|
:Menampilkan popup konfirmasi;

|Pengguna|
if () then (Konfirmasi ok)
  |Sistem|
  :Menghapus session pengguna;

  |DBMS|
  :Menghapus token session pengguna;

  fork
    :Menampilkan pesan berhasil;
  fork again
    :Menampilkan halaman peta bencana;
  endfork
else (Konfirmasi batal)
endif 

|Pengguna|
stop
@enduml