@startuml UC-AUTH-002 - Login
!pragma useVerticalIf on

title Login

|Pengguna|
start
:Memilih menu login;

|Sistem|
:Menampilkan menu login;

|Pengguna|
:Mengisi data akun;
:Mengklik tombol login;

|Sistem|
:Mengecek hasil hash kredensial;
if () then (Kredensial benar)
  :Menyimpan session pengguna;
  :Menampilkan pesan berhasil;
  :Menampilkan halaman peta bencana;
else (Kredensial salah)
  :Tampilkan pesan login gagal;
endif 

stop
@enduml