@startuml Memulihkan akun lupa password
!pragma useVerticalIf on

title Memulihkan akun lupa password

|Pengguna|
start

:Memilih menu login;

|Sistem|
:Menampilkan menu login;

|Pengguna|
:Memilih tombol "Lupa password";

|Sistem|
:Menampilkan menu lupa password;

|Pengguna|
:Mengisi alamat email akun;

|DBMS|
:Mencari apakah alamat email sudah terdaftar;

|Sistem|
if (Email terdaftar?) then (Ya)
  :Meng-enable-kan tombol lanjut;

  |Pengguna|
  :Mengklik tombol lanjut;

  |Email Service|
  :Mengirim kode OTP ke alamat email akun;

  |Sistem|
  :Menampilkan pesan Kode OTP telah dikirimkan;
  :Menampilkan menu kode OTP;

  |Pengguna|
  :Mengisi kode OTP;
  
  |Sistem|
  :Mengecek kode OTP;

  if (Kode OTP sesuai?) then (Tidak)
  else (Ya)
    :Menampilkan menu ubah password;

    |Pengguna|
    :Mengisi password baru;
    :Mengklik tombol simpan;

    |DBMS|
    :Menyimpan password baru;

    |Sistem|
    :Menampilkan pesan berhasil;
    :Menampilkan menu login;
  endif
else (Tidak)
  :Menampilkan pesan email tidak terdaftar;
endif

stop
@enduml