@startuml UC-AUTH-001 - Registrasi
skinparam wrapWidth 140

title Registrasi

|Pengguna|
start
:Memilih menu registrasi;

|Sistem|
:Menampilkan menu registrasi;

|Pengguna|
:Memilih metode registrasi;

if () then (Email)
  :Mengisi data registrasi;

  |DBMS|
  :Mencari apakah email sudah terdaftar atau belum;

  |Sistem|
  if () then (Email tidak terdaftar)
    fork
      :Tampilkan warna accent success pada input email;
    fork again
      :Meng-enable-kan tombol daftar;
    end fork

    |Pengguna|
    :Mengklik tombol daftar;
  else (Email terdaftar)
  |Sistem|
    :Tampilkan pesan email sudah terdaftar;
  endif
else (OAuth)
  |OAuth Provider|
  :Menerima data pengguna dari provider OAuth;
endif 

    |Sistem|
    :Menampilkan popup konfirmasi;

    |Pengguna|
    :Mengonfirmasi data pendaftaran;
    if () then (Konfirmasi ok)
      |DBMS|
      :Menyimpan data registrasi;

      |Sistem|
      fork
        :Menampilkan pesan berhasil;
      fork again
        :Menampilkan halaman peta bencana;
      end fork
    else (Konfirmasi batal)
    endif

|Pengguna|
stop
@enduml