@startuml UC-AUTH-001 - Registrasi OAuth
skinparam wrapWidth 140

title Registrasi OAuth

actor ":User" as user
participant ":RegisterUI" as view
participant ":AuthController" as controller
participant ":AuthService" as authService
participant ":UserService" as userService
participant "GoogleOAuthProvider:OAuthProvider" as oauth
database ":DBMS" as db

user -> view ++: Open register view
view -> view: showRegisterView()

user -> view: Register using Google
view -> controller ++: registerOAuth()

controller -> authService ++: requestOAuth()

authService -> oauth ++: requestAuth(appId, callbackUrl)
oauth --> authService: oauthUrl

authService --> controller --: oauthUrl

controller --> view: oauthUrl

view -> view ++: openOAuthUrl(oauthUrl)
user -> view: Authenticate Google account
deactivate view

opt user's OAuth authenticated
  oauth -> controller: oauthCallback(url, oauthCode)
  controller --> oauth
  deactivate oauth

  controller -> authService ++: createOAuthToken(oauthCode)
  authService -> oauth ++: getToken(oauthCode)
  oauth --> authService --: token
  authService -> db ++: insertToken()
  db --> authService --: transactionStatus
  authService --> controller --: token

  controller -> authService ++: getNewUserData(token)
  authService -> oauth ++: getCurrentUserProfile(token)
  oauth --> authService --: userProfileDTO

  authService -> userService ++: createUser(userCreateDTO)

  userService -> db ++: insertUser()
  db --> userService --: transactionStatus
  userService --> authService --: userModel
  authService --> controller --: userModel

  controller --> view --: userDTO, token

  view -> view: setUserSession(userDTO, token)
end
