@startuml UC-MGACCOUNT-003 - Mengubah password 
skinparam wrapWidth 140

title Mengubah password

|Pengguna|
:Memilih menu edit akun;

|DBMS|
:Mengambil data akun;

|Sistem|
:Menampilkan menu edit;

|Pengguna|
:Mengklik tombol ubah password;

|Sistem|
:Menampilkan popup isian password baru;

|Pengguna|
:Mengisi password lama;
:Mengisi password baru;
:Mengklik tombol lanjut;

|Sistem|
:Menampilkan popup konfirmasi;

|Pengguna|
:Mengonfirmasi perubahan password;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |Sistem|
  :Meng-hash data password lama & baru;

  |DBMS|
  :Mengecek kebenaran password lama;

  if () then (Password lama benar)
    |DBMS|
    :Menyimpan password baru;

    |Sistem|
    fork
      :Menampilkan pesan berhasil;
    fork again
      :Menampilkan menu edit akun;
    endfork
  else (Password lama salah)
    |Sistem|
    :Menampilkan pesan password lama salah;
  endif
endif

|Pengguna|
stop

@enduml