@startuml UC-MGACCOUNT-003 - Mengubah password 
skinparam wrapWidth 140

title Mengubah password

|Pengguna|
:Memilih menu edit akun;

|Sistem|
:Menampilkan menu edit;

|Pengguna|
:Mengklik tombol ubah password;

|Sistem|
:Menampilkan popup isian password baru;

|Pengguna|
:Mengisi password lama;
:Mengisi password baru;
:Mengklik tombol lanjut;

|Sistem|
:Menampilkan popup konfirmasi;

|Pengguna|
:Mengonfirmasi perubahan password;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |DBMS|
  :Menyimpan perubahan password;

  |Sistem|
  fork
    :Menampilkan pesan berhasil;
  fork again
    :Menampilkan menu edit akun;
  endfork
endif

|Pengguna|
stop

@enduml