@startuml UC-MGACCOUNT-002 - Mengubah email
skinparam wrapWidth 140

title Mengubah email
|Pengguna|
:Memilih menu edit akun;

|DBMS|
:Mengambil data akun;

|Sistem|
:Menampilkan menu edit;

|Pengguna|
:Mengklik tombol ubah email;

|Sistem|
:Menampilkan popup isian email baru;

|Pengguna|
:Mengisi alamat email baru;

|DBMS|
:Mencari apakah alamat email sudah terdaftar;

|Sistem|
if () then (Email belum terdaftar)
  |Email Service|
  :Mengirim kode OTP ke alamat email akun;

  |Sistem|
  fork
    :Menampilkan pesan Kode OTP telah dikirimkan;
  fork again
    :Menampilkan menu kode OTP;
  endfork

  |Pengguna|
  :Mengisi kode OTP;
  
  |Sistem|
  :Mengecek kode OTP;

  if () then (OTP tidak sesuai)
    :Menampilkan pesan kode OTP salah;
  else (OTP sesuai)
    |DBMS|
    :Menyimpan email baru;

    |Sistem|
    fork
      :Menampilkan pesan berhasil;
    fork again
      :Menampilkan menu edit akun;
    endfork
  endif
else (Email sudah terdaftar)
  :Menampilkan pesan email sudah terdaftar;
endif

stop

@enduml