@startuml UC-MGACCOUNT-004 - Menghapus akun
skinparam wrapWidth 140

title Menghapus akun

|Pengguna|
:Memilih menu edit akun;

|Sistem|
:Menampilkan menu edit;

|Pengguna|
:Mengklik tombol hapus akun;

|Sistem|
:Menampilkan popup isian alasan;

|Pengguna|
:Mengisi alasan penghapusan;
:Mengklik tombol lanjut;

|Sistem|
:Menampilkan popup konfirmasi;

|Pengguna|
:Mengisi password akun;
:Mengonfirmasi penghapusan akun;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |DBMS|
  :Menghapus akun;

  |Sistem|
  fork
    :Menampilkan pesan berhasil;
  fork again
    :Menampilkan peta bencana;
  endfork
endif

|Pengguna|
stop

@enduml