@startuml UC-MGACCOUNT-003 - Mengubah password 
title Mengubah password

|Pengguna|
:Memilih menu edit akun;

|Sistem|
:Menampilkan menu edit;

|Pengguna|
:Mengklik tombol ubah password;

|Sistem|
:Menampilkan popup isian password baru;

|Pengguna|
:Mengisi password lama;
:Mengisi password baru;
:Mengklik tombol lanjut;

|Sistem|
:Menampilkan popup konfirmasi;

|Pengguna|
:Mengonfirmasi perubahan password;

if (Konfirmasi popup) then (Batal)
else (Ok)
  |DBMS|
  :Menyimpan perubahan password;

  |Sistem|
  :Menampilkan pesan berhasil;
  :Menampilkan menu edit akun;
endif

|Pengguna|
stop

@enduml