@startuml UC-MGACCOUNT-002 - Mengubah email
title Mengubah email

|Pengguna|
:Memilih menu edit akun;

|Sistem|
:Menampilkan menu edit;

|Pengguna|
:Mengklik tombol ubah email;

|Sistem|
:Menampilkan popup isian email baru;

|Pengguna|
:Mengisi alamat email baru;

|DBMS|
:Mencari apakah alamat email sudah terdaftar;

|Sistem|
if () then (Email belum terdaftar)
  :Meng-enable-kan tombol lanjut;

  |Pengguna|
  :Mengklik tombol lanjut;

  |Email Service|
  :Mengirim kode OTP ke alamat email akun;

  |Sistem|
  :Menampilkan pesan Kode OTP telah dikirimkan;
  :Menampilkan menu kode OTP;

  |Pengguna|
  :Mengisi kode OTP;
  
  |Sistem|
  :Mengecek kode OTP;

  if () then (OTP tidak sesuai)
    :Menampilkan pesan kode OTP salah;
  else (OTP sesuai)
    |DBMS|
    :Menyimpan email baru;

    |Sistem|
    :Menampilkan pesan berhasil;
    :Menampilkan menu edit akun;
  endif
else (Email sudah terdaftar)
  :Menampilkan pesan email sudah terdaftar;
endif

stop

@enduml