@startuml UC-MGACCOUNT-001 - Mengubah data akun
skinparam wrapWidth 140

title Mengubah data akun

|Pengguna|
:Memilih menu edit akun;

|DBMS|
:Mengambil data akun;

|Sistem|
:Menampilkan menu edit;

|Pengguna|
:Mengisi isian data akun;
:Mengunggah foto profil baru;

|Sistem|
:Menampilkan preview foto profil baru;

|Pengguna|
:Mengklik tombol simpan;

|Sistem|
:Menampilkan popup konfirmasi;

|Pengguna|
:Mengonfirmasi perubahan data;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |Sistem|
  :Memvalidasi data akun;

  if () then (Data tidak valid)
    |Sistem|
    :Menampilkan pesan error validasi;
  else (Data valid)
    |DBMS|
    :Menyimpan perubahan data akun;

    |Storage Bucket|
    if () then (Tidak ada unggahan foto profil)
    else (Ada unggahan foto profil)
      :Menyimpan foto profil;
    endif

    |Sistem|
    fork
      :Menampilkan pesan berhasil;
    fork again
      :Menampilkan menu edit akun;
    endfork
  endif
endif

|Pengguna|
stop

@enduml