@startuml UC-MGUSER-010 - Membuat daftar akun khusus
title Membuat daftar akun khusus

|Administrator|
start
:Memilih menu daftar akun khusus;
:Memilih filter dan sort;

|Sistem|
:Menampilkan menu daftar akun khusus;

|Administrator|
:Memilih menu tambah akun;

|Sistem|
:Menampilkan menu tambah akun khusus;

|Administrator|
:Mengisi data akun khusus;

|DBMS|
:Mencari apakah email sudah terdaftar atau belum;

|Sistem|
if () then (Email belum terdaftar)
  |Sistem|
  :Meng-enable-kan tombol simpan;

  |Administrator|
  :Mengklik tombol simpan;
  
  |Sistem|
  :Menampilkan popup konfirmasi;

  |Administrator|
  :Mengonfirmasi pembuatan akun khusus;

  if () then (Konfirmasi batal)
  else (Konfirmasi ok)
    |DBMS|
    :Menyimpan akun baru;

    |Sistem|
    :Menampilkan pesan berhasil;
    :Menampilkan menu daftar akun khusus;
  endif
else (Email sudah terdaftar)
  :Menampilkan pesan email sudah terdaftar;
endif

stop

@enduml