@startuml UC-MGUSER-007 - Mengubah role pengguna
skinparam wrapWidth 140

title Mengubah role pengguna

|Administrator|
start
:Memilih menu edit role pengguna;

|DBMS|
:Mengambil data role pengguna dan anggotanya;
:Mengambil data akun-akun khusus terdaftar;

|Sistem|
:Menampilkan menu edit role pengguna;
:Menampilkan daftar pengguna yang memiliki role tersebut;

|Administrator|
:Mengisi isian nama role;
:Memilih module (halaman) apa saja yang dapat diakses oleh role;
:Mengklik tombol tambah anggota;

|Sistem|
:Menampilkan popup berisi pilihan akun-akun khusus terdaftar;

|Administrator|
:Memilih akun-akun khusus yang akan menjadi anggota dari role;
:Memilih tombol simpan;

|Sistem|
:Menampilkan konfirmasi;

|Administrator|
:Mengonfirmasi perubahan role;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |Sistem|
  :Memvalidasi data role dan anggota role;

  if () then (Data tidak valid)
    :Menampilkan pesan error validasi;
  else (Data valid)
    |DBMS|
    :Menyimpan perubahan role;
    :Menyimpan anggota-anggota dari role;

    |Sistem|
    fork
      :Menampilkan pesan berhasil;
    fork again
      :Menampilkan menu detail role pengguna;
    endfork
  endif
endif

|Administrator|
stop

@enduml