@startuml UC-MGUSER-012 - Mengubah data akun khusus
title Mengubah data akun khusus

|Administrator|
start
:Memilih menu daftar akun khusus;
:Memilih filter dan sort;

|Sistem|
:Menampilkan menu daftar akun khusus;

|Administrator|
:Memilih tombol edit pada akun khusus yang dipilih;

|Sistem|
:Menampilkan menu edit akun khusus;

|Administrator|
:Mengisi data akun khusus;

|DBMS|
:Mencari apakah email sudah terdaftar atau belum;

|Sistem|
if (Email sudah terdaftar?) then (Sudah terdaftar)
else (Belum terdaftar)
  :Meng-enable-kan tombol simpan;

  |Administrator|
  :Mengklik tombol simpan;
  
  |Sistem|
  :Menampilkan popup konfirmasi;

  |Administrator|
  :Mengonfirmasi pembuatan akun khusus;

  if (Konfirmasi popup) then (Batal)
  else (Ok)
    |DBMS|
    :Menyimpan perubahan data akun khusus;

    |Sistem|
    :Menampilkan pesan berhasil;
    :Menampilkan menu detail akun khusus;
  endif
endif

|Administrator|
stop

@enduml