@startuml UC-MGUSER-008 - Menghapus role pengguna
skinparam wrapWidth 140

title Menghapus role pengguna

|Administrator|
start
:Memilih menu detail role pengguna;

|DBMS|
:Mengambil data role pengguna dan anggotanya;
:Mengambil data akun-akun khusus terdaftar;

|Sistem|
:Menampilkan menu detail role pengguna;
:Menampilkan daftar pengguna yang memiliki role tersebut;

|Administrator|
:Mengklik tombol hapus;

|Sistem|
:Menampilkan popup isian alasan;

|Administrator|
:Mengisi alasan penghapusan;

|Sistem|
:Menampilkan konfirmasi;

|Administrator|
:Mengonfirmasi penghapusan role;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |Sistem|
  :Memvalidasi alasan penghapusan role;

  if () then (Data alasan tidak valid)
    :Menampilkan pesan error validasi;
  else (Data alasan valid)
    |DBMS|
    :Menghapus role dari anggota yang sebelumnya termasuk;
    :Menghapus role;

    |Sistem|
    fork
      :Menampilkan pesan berhasil;
    fork again
      :Menampilkan menu daftar role pengguna;
    endfork
  endif
endif

|Administrator|
stop

@enduml