@startuml UC-MGUSER-014 - Menghapus akun khusus
title Menghapus akun khusus

|Administrator|
start
:Memilih menu daftar akun khusus;
:Memilih filter dan sort;

|Sistem|
:Menampilkan menu daftar akun khusus;

|Administrator|
:Memilih tombol detail pada akun khusus yang dipilih;

|Sistem|
:Menampilkan menu detail akun khusus;

|Administrator|
:Mengklik tombol hapus akun;

|Sistem|
:Menampilkan popup isian alasan;

|Administrator|
:Mengisi alasan penghapusan;
:Mengklik tombol hapus pada popup;

|Sistem|
:Menampilkan konfirmasi;

|Administrator|
:Mengonfirmasi penghapusan akun;

if (Konfirmasi popup) then (Batal)
else (Ok)
  |DBMS|
  :Menghapus akun;

  |Sistem|
  :Menampilkan pesan berhasil;
  :Menampilkan menu daftar akun khusus;
endif

|Administrator|
stop

@enduml