@startuml UC-MGUSER-002 - Menonaktifkan pengguna terdaftar
skinparam wrapWidth 140

title Menonaktifkan pengguna terdaftar

|Administrator|
start
:Memilih menu daftar pengguna;
:Memilih filter dan sort;

|DBMS|
:Mengambil data pengguna-pengguna;

|Sistem|
:Menampilkan menu daftar pengguna;

|Administrator|
:Mengklik tombol nonaktifkan pada pengguna yang dipilih;
:Mengisi alasan penonaktifan;

|Sistem|
:Menampilkan konfirmasi;

|Administrator|
:Mengonfirmasi penonaktifan pengguna;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |Sistem|
  :Memvalidasi alasan penonaktifan;

  if () then (Data alasan tidak valid)
    :Menampilkan pesan error validasi;
  else (Data alasan valid)
    |DBMS|
    :Menyimpan penonaktifan pengguna;

    |Sistem|
    fork
      :Menampilkan pesan berhasil;
    fork again
      :Menampilkan menu daftar pengguna;
    endfork
  endif
endif

|Administrator|
stop

@enduml