@startuml UC-MGUSER-011 - Melihat detail akun khusus
skinparam wrapWidth 140

title Melihat detail akun khusus (Administrator / Perwakilan BPBD)

|Administrator|
start
:Memilih menu detail akun khusus;

|DBMS|
:Mengambil data akun khusus & log aktivitasnya;

|Sistem|
:Menampilkan menu detail akun khusus;
:Menampilkan log aktivitas akun khusus;

stop

@enduml