@startuml UC-MGUSER-012 - Mengubah data akun khusus
skinparam wrapWidth 140

title Mengubah data akun khusus

|Administrator|
start
:Memilih menu edit pada akun khusus yang dipilih;

|DBMS|
:Mengambil data detail akun khusus;

|Sistem|
:Menampilkan menu edit akun khusus;

|Administrator|
:Mengisi data akun khusus;

|Sistem|
:Memvalidasi data akun;

if () then (Data tidak valid)
  :Menampilkan pesan error validasi;
else (Data valid)
  |DBMS|
  :Mencari apakah email sudah terdaftar atau belum;

  |Sistem|
  if () then (Email belum terdaftar)
    :Menampilkan popup konfirmasi;

    |Administrator|
    :Mengonfirmasi pembuatan akun khusus;

    if () then (Konfirmasi batal)
    else (Konfirmasi ok)
      |DBMS|
      :Menyimpan perubahan data akun khusus;

      |Sistem|
      fork
        :Menampilkan pesan berhasil;
      fork again
        :Menampilkan menu detail akun khusus;
      endfork
    endif
  else (Email sudah terdaftar)
    |Sistem|
    :Menampilkan pesan email sudah terdaftar;
  endif
endif

stop

@enduml