@startuml UC-MGUSER-004 - Melihat daftar role pengguna
skinparam wrapWidth 140

title Melihat daftar role pengguna

|Administrator|
start
:Memilih menu daftar role pengguna;
:Memilih filter dan sort;

|DBMS|
:Mengambil data role-role pengguna;

|Sistem|
:Menampilkan menu daftar role pengguna;

stop

@enduml