@startuml UC-MGUSER-001 - Melihat daftar pengguna
skinparam wrapWidth 140

title Melihat daftar pengguna

|Administrator|
start
:Memilih menu daftar pengguna;
:Memilih filter dan sort;

|Sistem|
:Menampilkan menu daftar pengguna;

stop

@enduml