@startuml UC-MGUSER-013 - Menonaktifkan akun khusus
skinparam wrapWidth 140

title Menonaktifkan akun khusus

|Administrator|
start
:Memilih menu detail pada akun khusus yang dipilih;

|DBMS|
:Mengambil data detail akun khusus;

|Sistem|
:Menampilkan menu detail akun khusus;

|Administrator|
:Mengklik tombol nonaktifkan akun;

|Sistem|
:Menampilkan popup isian alasan;

|Administrator|
:Mengisi alasan penonaktifan;

|Sistem|
:Menampilkan konfirmasi;

|Administrator|
:Mengonfirmasi penonaktifan akun;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  if () then (Data alasan tidak valid)
    |Sistem|
    :Menampilkan pesan error validasi;
  else (Data alasan valid)
    |DBMS|
    :Menyimpan penonaktifan akun;

    |Sistem|
    fork
      :Menampilkan pesan berhasil;
    fork again
      :Menampilkan menu detail akun khusus;
    endfork
  endif
endif

|Administrator|
stop

@enduml