@startuml UC-MGUSER-005 - Melihat detail role pengguna
skinparam wrapWidth 140

title Melihat detail role pengguna

|Administrator|
start
:Memilih menu daftar role pengguna;
:Memilih filter dan sort;

|Sistem|
:Menampilkan menu daftar role pengguna;

|Administrator|
:Memilih tombol detail pada role pengguna yang dipilih;

|Sistem|
fork
  :Menampilkan detail role pengguna yang dipilih;
fork again
  :Menampilkan daftar pengguna yang memiliki role tersebut;
endfork

stop

@enduml