@startuml UC-MGUSER-008 - Menghapus role pengguna
skinparam wrapWidth 140

title Menghapus role pengguna

|Administrator|
start
:Memilih menu daftar role pengguna;
:Memilih filter dan sort;

|Sistem|
:Menampilkan menu daftar role pengguna;

|Administrator|
:Memilih tombol detail pada role pengguna;

|Sistem|
fork
  :Menampilkan menu detail role pengguna;
fork again
  :Menampilkan daftar pengguna yang memiliki role tersebut;
endfork

|Administrator|
:Mengklik tombol hapus;

|Sistem|
:Menampilkan popup isian alasan;

|Administrator|
:Mengisi alasan penghapusan;

|Sistem|
:Menampilkan konfirmasi;

|Administrator|
:Mengonfirmasi perubahan role;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |DBMS|
  :Menghapus role dari anggota yang sebelumnya termasuk;
  :Menghapus role;

  |Sistem|
  fork
  :Menampilkan pesan berhasil;
  fork again
  :Menampilkan menu daftar role pengguna;
  endfork
endif

|Administrator|
stop

@enduml