@startuml UC-MGUSER-003 - Melihat daftar pengguna nonaktif
title Melihat daftar pengguna nonaktif

|Administrator|
start
:Memilih menu daftar pengguna nonaktif;
:Memilih filter dan sort;

|Sistem|
:Menampilkan menu daftar pengguna nonaktif;

stop

@enduml