@startuml UC-MGUSER-006 - Membuat role pengguna
skinparam wrapWidth 140

title Membuat role pengguna

|Administrator|
start
:Memilih menu daftar role pengguna;
:Memilih filter dan sort;

|Sistem|
:Menampilkan menu daftar role pengguna;

|Administrator|
:Memilih menu tambah role pengguna;

|Sistem|
:Menampilkan menu tambah role pengguna;

|Administrator|
:Mengisi isian nama role;
:Memilih module (halaman) apa saja yang dapat diakses oleh role;
:Mengklik tombol tambah anggota;

|Sistem|
:Menampilkan popup berisi pilihan akun-akun khusus terdaftar;

|Administrator|
:Memilih akun-akun khusus yang akan menjadi anggota dari role;
:Memilih tombol simpan;

|Sistem|
:Menampilkan konfirmasi;

|Administrator|
:Mengonfirmasi pembuatan role;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |DBMS|
  :Menyimpan role baru;
  :Menyimpan anggota-anggota dari role baru;

  |Sistem|
  fork
    :Menampilkan pesan berhasil;
  fork again
    :Menampilkan menu detail role pengguna;
  endfork
endif

|Administrator|
stop

@enduml