@startuml UC-MGUSER-013 - Menonaktifkan akun khusus
skinparam wrapWidth 140

title Menonaktifkan akun khusus

|Administrator|
start
:Memilih menu daftar akun khusus;
:Memilih filter dan sort;

|Sistem|
:Menampilkan menu daftar akun khusus;

|Administrator|
:Memilih tombol detail pada akun khusus yang dipilih;

|Sistem|
:Menampilkan menu detail akun khusus;

|Administrator|
:Mengklik tombol nonaktifkan akun;

|Sistem|
:Menampilkan popup isian alasan;

|Administrator|
:Mengisi alasan penonaktifan;
:Mengklik tombol nonaktifkan pada popup;

|Sistem|
:Menampilkan konfirmasi;

|Administrator|
:Mengonfirmasi penonaktifan akun;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |DBMS|
  :Menyimpan penonaktifan akun;

  |Sistem|
  fork
    :Menampilkan pesan berhasil;
  fork again
    :Menampilkan menu detail akun khusus;
  endfork
endif

|Administrator|
stop

@enduml