@startuml UC-MGUSER-003 - Melihat daftar pengguna nonaktif
skinparam wrapWidth 140

title Melihat daftar pengguna nonaktif

|Administrator|
start
:Memilih menu daftar pengguna nonaktif;
:Memilih filter dan sort;

|DBMS|
:Mengambil data pengguna-pengguna;

|Sistem|
:Menampilkan menu daftar pengguna nonaktif;

stop

@enduml