@startuml UC-MAP-015 - Melaporkan komentar lain

title Melaporkan komentar lain
 
|Pengguna|
start
:Memilih menu komentar;

|Sistem|
:Menampilkan komentar;

|Pengguna|
:Memilih menu laporkan pada komentar yang telah dibuat;

|Sistem|
:Menampilkan form laporan komentar;

|Pengguna|
:Mengisi alasan laporan;
:Mengklik tombol kirim;

|Sistem|
:Menampilkan konfirmasi;

|Pengguna|
:Mengonfirmasi laporan;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |DBMS|
  :Menyimpan laporan;

  |Sistem|
  :Menampilkan pesan berhasil menyimpan laporan;
  :Menampilkan daftar komentar;
endif

|Pengguna|
stop

@enduml