@startuml UC-MAP-015 - Melaporkan komentar lain
skinparam wrapWidth 140

title Melaporkan komentar lain
 
|Pengguna|
start
:Memilih menu komentar;

|DBMS|
:Mengambil data komentar-komentar;

|Sistem|
:Menampilkan komentar;

|Pengguna|
:Memilih menu laporkan pada komentar yang telah dibuat;

|Sistem|
:Menampilkan form laporan komentar;

|Pengguna|
:Mengisi alasan laporan;

|Sistem|
:Memvalidasi isi alasan laporan;

if () then (Alasan valid)
  :Menampilkan konfirmasi;

  |Pengguna|
  :Mengonfirmasi laporan;

  if () then (Konfirmasi batal)
  else (Konfirmasi Ok)
    |DBMS|
    :Menyimpan laporan;

    |Sistem|
    fork
      :Menampilkan pesan berhasil menyimpan laporan;
    fork again
      :Menampilkan daftar komentar;
    endfork
  endif
else (Alasan tidak valid)
  |Sistem|
  :Tampilkan pesan error validasi;
endif

stop

@enduml