@startuml UC-MAP-019 - Menghapus laporan bencana alam yang telah diajukan
skinparam wrapWidth 140

title Menghapus laporan bencana alam yang telah diajukan

|Pengguna|
start
:Memilih menu laporan bencana alam;

|Sistem|
:Menampilkan menu laporan bencana alam;

|Pengguna|
:Memilih tombol hapus pada laporan yang telah dipilih;

|Sistem|
:Menampilkan popup konfirmasi;

|Pengguna|
:Mengonfirmasi penghapusan;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |DBMS|
  :Menghapus laporan;

  |Storage Bucket|
  if () then (Tidak ada unggahan)
  else (Ada unggahan)
    :Menghapus media unggahan;
  endif

  |Sistem|
  :Menampilkan pesan berhasil;
endif

|Pengguna|
stop

@enduml