@startuml UC-MAP-009 - Melihat komentar pada bencana alam
skinparam wrapWidth 140

title Melihat komentar pada bencana alam
 
|Pengguna|
start
:Memilih menu komentar pada detail bencana alam;

|DBMS|
:Mengambil komentar dari bencana alam;

|Sistem|
if () then (Tidak ada komentar)
  :Menampilkan pesan tidak ada komentar;
else (Ada komentar)
  :Menampilkan komentar dari bencana alam;
endif

stop

@enduml