@startuml UC-MAP-013 - Mengubah komentar yang dibuat 
skinparam wrapWidth 140

title Mengubah komentar yang dibuat
 
|Pengguna|
start
:Memilih menu komentar;

|DBMS|
:Mengambil data komentar-komentar;

|Sistem|
:Menampilkan komentar;

|Pengguna|
:Memilih menu edit pada komentar yang telah dibuat;
:Menginputkan konten komentar;
:Memilih media (gambar atau video) untuk dilampirkan;

|Sistem|
:Memvalidasi data komentar;

if () then (Data valid)
  |DBMS|
  :Menyimpan komentar;

  |Storage Bucket|
  if () then (Tidak ada unggahan)
  else (Ada unggahan)
  :Menyimpan media unggahan;
  endif

  |Sistem|
  fork
    :Menampilkan pesan berhasil diubah;
  fork again
    :Menampilkan komentar yang telah diubah;
  endfork
else (Data tidak valid)
  |Sistem|
  :Tampilkan pesan error validasi;
endif

stop

@enduml