@startuml UC-MAP-018 - Mengubah laporan bencana alam yang telah diajukan
skinparam wrapWidth 140

title Mengubah laporan bencana alam yang telah diajukan

|Pengguna|
start
:Memilih menu laporan bencana alam;

|Sistem|
:Menampilkan menu laporan bencana alam;

|Pengguna|
:Memilih tombol edit pada laporan yang telah dipilih;
:Mengisi jenis, lokasi, dan deskripsi bencana alam;
:Mengunggah media (foto atau video) terkait bencana alam;
:Mengklik tombol laporkan;

|Sistem|
:Menampilkan popup konfirmasi;

|Pengguna|
:Mengonfirmasi popup;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |DBMS|
  :Menyimpan perubahan laporan;

  |Storage Bucket|
  if () then (Tidak ada unggahan)
  else (Ada unggahan)
    :Menyimpan media unggahan;
  endif

  |Sistem|
  fork
    :Menampilkan pesan berhasil;
  fork again
    :Menampilkan detail laporan yang telah dibuat;
  endfork
endif

|Pengguna|
stop

@enduml