@startuml UC-MAP-009 - Melihat komentar pada bencana alam

title Melihat komentar pada bencana alam
 
|Pengguna|
start
:Memilih bencana alam pada peta;

|Sistem|
:Zoom in ke daerah sekitar bencana alam;
:Menampilkan detail bencana alam;

|Pengguna|
:Memilih menu komentar;

|Sistem|
:Menampilkan komentar dari bencana alam;

if () then (Tidak ada komentar)
  :Menampilkan pesan tidak ada komentar;
else (Ada komentar)
endif

stop

@enduml