@startuml UC-MAP-013 - Mengubah komentar yang dibuat 

title Mengubah komentar yang dibuat
 
|Pengguna|
start
:Memilih menu komentar;

|Sistem|
:Menampilkan komentar;

|Pengguna|
:Memilih menu edit pada komentar yang telah dibuat;
:Menginputkan konten komentar;
:Memilih media (gambar atau video) untuk dilampirkan;
:Mengklik tombol unggah / komentar;

|DBMS|
:Menyimpan komentar;

|Storage Bucket|
if () then (Tidak ada unggahan)
else (Ada unggahan)
:Menyimpan media unggahan;
endif

|Sistem|
:Menampilkan pesan berhasil diubah;
:Menampilkan komentar yang telah diubah;

stop

@enduml