@startuml UC-MAP-001 - Melihat bencana alam sekitar sesuai lokasi saat ini
skinparam wrapWidth 140

title Melihat bencana alam sekitar sesuai lokasi saat ini

|Pengguna|
start
:Mengklik tombol cari lokasi / precise location;

|Browser Geolocation API|
:Mencari lokasi pengguna dengan geolocation;

|Sistem|
switch ()
case (Ditemukan)
  fork
    :Menampilkan data bencana alam sesuai lokasi pengguna;
  fork again
    :Zoom in ke daerah lokasi pengguna;
  fork again
    :Menampilkan rekapitulasi data bencana alam;
  endfork
case (Tidak ditemukan)
  :Tampilkan pesan lokasi tidak ditemukan;
case (Di luar Indonesia)
  :Tampilkan pesan lokasi berada di luar Indonesia;
endswitch

stop

@enduml