@startuml UC-MAP-001 - Melihat bencana alam sekitar sesuai lokasi saat ini
skinparam wrapWidth 140

title Melihat bencana alam sekitar sesuai lokasi saat ini

|Pengguna|
start
:Mengklik tombol cari lokasi / precise location;

|Browser Geolocation API|
:Meminta permission penggunaan geolocation;

if () then (Mendapat permission)
  :Mencari lokasi pengguna dengan geolocation;

  |Sistem|
  if () then (Lokasi tidak tersedia)
    :Tampilkan pesan layanan lokasi tidak tersedia;
  else (Lokasi ditemukan)
    |DBMS|
    :Mengambil data bencana alam sesuai lokasi;

    fork
      :Menampilkan pin-pin titik bencana alam sesuai lokasi pengguna;
    fork again
      :Menampilkan rekapitulasi data bencana alam;
    endfork

    |Map API|
    :Zoom in ke daerah lokasi pengguna;
  endif
else (Tidak mendapat permission)
  |Sistem|
  :Tampilkan pesan layanan lokasi tidak diizinkan pengguna;
endif


stop

@enduml