@startuml UC-MAP-014 - Menghapus komentar yang dibuat 

title Menghapus komentar yang dibuat
 
|Pengguna|
start
:Memilih menu komentar;

|Sistem|
:Menampilkan komentar;

|Pengguna|
:Memilih menu hapus pada komentar yang telah dibuat;

|Sistem|
:Menampilkan konfirmasi;

|Pengguna|
:Mengonfirmasi penghapusan;

if () then (Konfirmasi ok)
  |DBMS|
  :Menghapus komentar;

  |Storage Bucket|
  if () then (Tidak ada unggahan)
  else (Ada unggahan)
  :Menghapus media unggahan;
  endif

  |Sistem|
  :Menampilkan pesan berhasil dihapus;
  :Menampilkan menu komentar;
else (Konfirmasi batal)
endif

|Pengguna|
stop

@enduml