@startuml UC-MAP-021 - Melaporkan laporan bencana alam yang diunggah pengguna lain
skinparam wrapWidth 140

title Melaporkan laporan bencana alam yang diunggah pengguna lain

|Pengguna|
start
:Memilih laporan bencana alam pada peta;

|DBMS|
:Mengambil data laporan bencana alam;

|Sistem|
:Menampilkan menu detail laporan bencana alam;

|Pengguna|
:Memilih menu laporan pada laporan yang dipilih;
:Mengisi alasan laporan;
:Mengklik tombol laporkan;

|Sistem|
:Menampilkan popup konfirmasi;

|Pengguna|
:Mengonfirmasi laporan;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |Sistem|
  :Memvalidasi alasan laporan;

  if () then (Alasan tidak valid)
    |Sistem|
    :Menampilkan pesan error validasi;
  else (Alasan valid)
    |DBMS|
    :Menyimpan laporan;
    
    |Sistem|
    fork
      :Menampilkan pesan berhasil;
    fork again
      :Menampilkan detail laporan bencana alam yang telah dilaporkan;
    endfork
  endif

endif

|Pengguna|
stop

@enduml