@startuml UC-MAP-002 - Melihat bencana alam sekitar sesuai lokasi yang dicari
skinparam wrapWidth 140

title Melihat bencana alam sekitar sesuai lokasi yang dicari

|Pengguna|
start
:Mengklik input pencarian lokasi;
:Menginputkan lokasi yang dicari;

|Sistem|
:Menampilkan rekomendasi lokasi;

|Pengguna|
:Mengklik tombol cari atau Enter;

|Sistem|
  fork
    :Menampilkan data bencana alam di sekitar lokasi yang dicari;
  fork again
    :Zoom in ke lokasi yang dicari;
  fork again
    :Menampilkan rekapitulasi data bencana alam;
  endfork

stop

@enduml