@startuml UC-MAP-017 - Membuat laporan bencana alam

title Membuat laporan bencana alam
 
|Pengguna|
start
:Memilih menu laporan bencana alam;

|Sistem|
:Menampilkan menu laporan bencana alam;

|Pengguna|
:Mengisi jenis, lokasi, dan deskripsi bencana alam;
:Mengunggah media (foto atau video) terkait bencana alam;
:Mengklik tombol laporkan;

|Sistem|
:Menampilkan popup konfirmasi;

|Pengguna|
:Mengonfirmasi popup;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |DBMS|
  :Menyimpan laporan;

  |Storage Bucket|
  if () then (Tidak ada unggahan)
  else (Ada unggahan)
    :Menyimpan media unggahan;
  endif

  |Sistem|
  :Menampilkan pesan berhasil;
  :Menampilkan detail laporan yang telah dibuat;
endif

|Pengguna|
stop

@enduml