@startuml UC-MAP-004 - Memfilter bencana alam dan laporan bencana alam yang ditampilkan
skinparam wrapWidth 140

title Memfilter bencana alam dan laporan bencana alam yang ditampilkan

|Pengguna|
start
:Memilih tombol filter;

|Sistem|
:Menampilkan menu overlay filter;

|Pengguna|
:Memilih filter yang digunakan;

|DBMS|
:Mengambil data bencana alam sesuai filter yang digunakan;

|Sistem|
if () then (Tidak ada bencana alam yang memenuhi)
  :Tampilkan pesan tidak ada bencana alam yang memenuhi kriteria;
else (Ada bencana alam yang memenuhi)
  :Menampilkan data bencana alam;
endif

stop

@enduml