@startuml UC-MAP-018 - Mengubah laporan bencana alam yang telah diajukan
skinparam wrapWidth 140

title Mengubah laporan bencana alam yang telah diajukan

|Pengguna|
start
:Memilih menu laporan bencana alam;

|Sistem|
:Menampilkan menu laporan bencana alam;

|Pengguna|
:Memilih tombol edit pada laporan yang telah dipilih;
:Mengisi jenis dan deskripsi bencana alam;

|Sistem|
:Menampilkan peta dengan titik lokasi sementara (lokasi placeholder);

|Pengguna|
repeat:Memilih metode pengisian lokasi;
if () then (Lokasi manual)
  |Pengguna|
  :Mengisi lokasi bencana alam;
 
else (Lokasi otomatis)
  |Geolocation Service|
  :Melakukan lookup/pencarian lokasi pengguna saat ini;
endif

|Sistem|
backward:Tampilkan pesan lokasi tidak ditemukan;
repeat while () is (Lokasi tidak ditemukan) not (Lokasi ditemukan)

|Sistem|
:Menampilkan titik lokasi bencana alam pada peta;

|Pengguna|
:Menyesuaikan (menggeser) titik lokasi pada peta;

|Pengguna|
:Mengunggah media (foto atau video) terkait bencana alam;
:Mengklik tombol laporkan;

|Sistem|
:Menampilkan popup konfirmasi;

|Pengguna|
:Mengonfirmasi popup;

if () then (Konfirmasi batal)
else (Konfirmasi Ok)
  |DBMS|
  :Menyimpan perubahan laporan;

  |Storage Bucket|
  if () then (Tidak ada unggahan)
  else (Ada unggahan)
    :Menyimpan media unggahan;
  endif

  |Sistem|
  fork
    :Menampilkan pesan berhasil;
  fork again
    :Menampilkan detail laporan yang telah dibuat;
  endfork
endif

|Pengguna|
stop

@enduml