@startuml UC-MAP-020 - Melihat daftar laporan bencana alam yang telah diajukan
skinparam wrapWidth 140

title Melihat daftar laporan alam yang telah diajukan

|Pengguna|
start
:Memilih menu laporan bencana alam;

|DBMS|
:Mengambil data laporan-laporan bencana alam;

|Sistem|
:Menampilkan laporan bencana alam;
stop

@enduml