@startuml UC-MAP-010 - Melihat komentar pada laporan bencana alam

title Melihat komentar pada laporan bencana alam
 
|Pengguna|
start
:Memilih laporan bencana alam pada peta;

|Sistem|
:Zoom in ke daerah sekitar laporan bencana alam;
:Menampilkan detail laporan bencana alam;

|Pengguna|
:Memilih menu komentar;

|Sistem|
:Menampilkan komentar dari laporan bencana alam;

if () then (Tidak ada komentar)
  :Menampilkan pesan tidak ada komentar;
else (Ada komentar)
endif

stop

@enduml