@startuml UC-MAP-016 - Memberikan like dislike pada komentar
skinparam wrapWidth 140

title Memberikan like dislike pada komentar
 
|Pengguna|
start
:Memilih menu komentar;

|Sistem|
:Menampilkan komentar;

|Pengguna|
:Memilih tombol like/dislike pada komentar;

|DBMS|
:Menyimpan like/dislike;

|Sistem|
:Menampilkan warna berbeda untuk tombol like/dislike;

stop

@enduml