@startuml UC-MAP-011 - Mengomentari pada bencana alam atau laporan bencana alam

title Mengomentari pada bencana alam atau laporan bencana alam
 
|Pengguna|
start
:Memilih menu komentar;

|Sistem|
:Menampilkan komentar;

|Pengguna|
:Menginputkan konten komentar;
:Memilih media (gambar atau video) untuk dilampirkan;
:Mengklik tombol unggah / komentar;

|DBMS|
:Menyimpan komentar;

|Storage Bucket|
if () then (Tidak ada unggahan)
else (Ada unggahan)
:Menyimpan media unggahan;
endif

|Sistem|
:Menampilkan pesan berhasil;
:Menampilkan komentar yang telah dibuat;

stop

@enduml