@startuml UC-MAP-004 - Memfilter bencana alam dan laporan bencana alam yang ditampilkan
skinparam wrapWidth 200

title Memfilter bencana alam dan laporan bencana alam yang ditampilkan

|Pengguna|
start
:Memilih tombol filter;

|Sistem|
:Menampilkan menu overlay filter;

|Pengguna|
:Memilih filter yang digunakan;
:Mengklik tombol filter;

|Sistem|
:Menampilkan data bencana alam sesuai filter yang digunakan;

if () then (Tidak ada bencana alam yang memenuhi)
  :Tampilkan pesan tidak ada bencana alam yang memenuhi kriteria;
else (Ada bencana alam yang memenuhi)
endif

stop

@enduml