@startuml UC-AUTH-004 - Memulihkan akun lupa password

title Memulihkan akun lupa password

actor ":User" as user
participant ":ForgotPasswordUI" as view
participant ":AuthController" as controller
participant ":AuthService" as authService
participant ":UserService" as userService
participant ":OTPService" as otpService
participant ":EmailService" as emailService
database ":DBMS" as db

user -> view ++: Open forgot password menu
view -> view: showForgotPasswordMenu()

user -> view: Enter email address
view -> controller ++: forgotPassword(email)
  controller -> authService ++: requestForgotPassword(email)
    authService -> userService ++: checkUserExistsByEmail(email)
      userService -> db ++: selectExistUser()
        return isUserExist
      return isUserExist
    
    alt user don't exist
      authService --> controller: invalidEmailErrorMessage
      controller --> view: errorMessages
      view -> view: showErrorMessages()
    else user exist
      authService -> otpService ++: sendOTP(email)
        otpService -> otpService ++: generateOTP()
          return otp
        
        otpService -> db ++: createOTPForEmail(email, otp)
          return transactionStatus

        otpService-> emailService ++: sendOTP(email, otp)
          return isEmailSent
        return isEmailSent
      return otpSentMessage

      return otpSentMessage
      view -> view: showOTPMenu()
      view -> view: showOTPSentMessage()

      user -> view: Input OTP

      view -> controller ++: validateOTP(email, otp)
        controller -> authService ++: validateOTP(email, otp)
          authService -> otpService ++: validateOTP(email, otp)
            otpService -> db ++: findOTP(email, otp)
              return isOtpFound
            return isOtpCorrect

            opt otp correct
              authService -> db ++: createResetPasswordToken(email)
                return resetPasswordToken
            end
          return isOtpCorrect, resetPasswordToken
        return isOtpCorrect, resetPasswordToken

      view -> view: showOTPStatusMessage(isOtpCorrect)
      
      opt otp correct
        view -> view: showResetPasswordPage()
        user -> view: Input new password

        view -> controller ++: resetPassword(resetPasswordToken, newPassword)
          controller -> authService ++: resetPassword(resetPasswordToken, newPassword)
            authService -> authService ++: hashPassword(newPassword)
              return passwordHash

            authService -> db ++: updateUserPasswordByResetPasswordToken(resetPasswordToken, passwordHash)
              return userModel
            return userModel
          
          return successMessage
        
        view -> view: showSuccessMessage()
      end

    end